// <auto-generated />
using System;
using CinemaBooking.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CinemaBooking.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250717100504_InitialModels")]
    partial class InitialModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CinemaBooking.API.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("CinemaBooking.API.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScreeningId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("CinemaBooking.API.Models.ReservationSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ReservationId")
                        .HasColumnType("integer");

                    b.Property<int>("SeatId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("SeatId");

                    b.ToTable("ReservationSeats");
                });

            modelBuilder.Entity("CinemaBooking.API.Models.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Screenings");
                });

            modelBuilder.Entity("CinemaBooking.API.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Column")
                        .HasColumnType("integer");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Column = 1,
                            Row = 1
                        },
                        new
                        {
                            Id = 2,
                            Column = 2,
                            Row = 1
                        },
                        new
                        {
                            Id = 3,
                            Column = 3,
                            Row = 1
                        },
                        new
                        {
                            Id = 4,
                            Column = 4,
                            Row = 1
                        },
                        new
                        {
                            Id = 5,
                            Column = 5,
                            Row = 1
                        },
                        new
                        {
                            Id = 6,
                            Column = 6,
                            Row = 1
                        },
                        new
                        {
                            Id = 7,
                            Column = 7,
                            Row = 1
                        },
                        new
                        {
                            Id = 8,
                            Column = 8,
                            Row = 1
                        },
                        new
                        {
                            Id = 9,
                            Column = 9,
                            Row = 1
                        },
                        new
                        {
                            Id = 10,
                            Column = 10,
                            Row = 1
                        },
                        new
                        {
                            Id = 11,
                            Column = 1,
                            Row = 2
                        },
                        new
                        {
                            Id = 12,
                            Column = 2,
                            Row = 2
                        },
                        new
                        {
                            Id = 13,
                            Column = 3,
                            Row = 2
                        },
                        new
                        {
                            Id = 14,
                            Column = 4,
                            Row = 2
                        },
                        new
                        {
                            Id = 15,
                            Column = 5,
                            Row = 2
                        },
                        new
                        {
                            Id = 16,
                            Column = 6,
                            Row = 2
                        },
                        new
                        {
                            Id = 17,
                            Column = 7,
                            Row = 2
                        },
                        new
                        {
                            Id = 18,
                            Column = 8,
                            Row = 2
                        },
                        new
                        {
                            Id = 19,
                            Column = 9,
                            Row = 2
                        },
                        new
                        {
                            Id = 20,
                            Column = 10,
                            Row = 2
                        },
                        new
                        {
                            Id = 21,
                            Column = 1,
                            Row = 3
                        },
                        new
                        {
                            Id = 22,
                            Column = 2,
                            Row = 3
                        },
                        new
                        {
                            Id = 23,
                            Column = 3,
                            Row = 3
                        },
                        new
                        {
                            Id = 24,
                            Column = 4,
                            Row = 3
                        },
                        new
                        {
                            Id = 25,
                            Column = 5,
                            Row = 3
                        },
                        new
                        {
                            Id = 26,
                            Column = 6,
                            Row = 3
                        },
                        new
                        {
                            Id = 27,
                            Column = 7,
                            Row = 3
                        },
                        new
                        {
                            Id = 28,
                            Column = 8,
                            Row = 3
                        },
                        new
                        {
                            Id = 29,
                            Column = 9,
                            Row = 3
                        },
                        new
                        {
                            Id = 30,
                            Column = 10,
                            Row = 3
                        },
                        new
                        {
                            Id = 31,
                            Column = 1,
                            Row = 4
                        },
                        new
                        {
                            Id = 32,
                            Column = 2,
                            Row = 4
                        },
                        new
                        {
                            Id = 33,
                            Column = 3,
                            Row = 4
                        },
                        new
                        {
                            Id = 34,
                            Column = 4,
                            Row = 4
                        },
                        new
                        {
                            Id = 35,
                            Column = 5,
                            Row = 4
                        },
                        new
                        {
                            Id = 36,
                            Column = 6,
                            Row = 4
                        },
                        new
                        {
                            Id = 37,
                            Column = 7,
                            Row = 4
                        },
                        new
                        {
                            Id = 38,
                            Column = 8,
                            Row = 4
                        },
                        new
                        {
                            Id = 39,
                            Column = 9,
                            Row = 4
                        },
                        new
                        {
                            Id = 40,
                            Column = 10,
                            Row = 4
                        },
                        new
                        {
                            Id = 41,
                            Column = 1,
                            Row = 5
                        },
                        new
                        {
                            Id = 42,
                            Column = 2,
                            Row = 5
                        },
                        new
                        {
                            Id = 43,
                            Column = 3,
                            Row = 5
                        },
                        new
                        {
                            Id = 44,
                            Column = 4,
                            Row = 5
                        },
                        new
                        {
                            Id = 45,
                            Column = 5,
                            Row = 5
                        },
                        new
                        {
                            Id = 46,
                            Column = 6,
                            Row = 5
                        },
                        new
                        {
                            Id = 47,
                            Column = 7,
                            Row = 5
                        },
                        new
                        {
                            Id = 48,
                            Column = 8,
                            Row = 5
                        },
                        new
                        {
                            Id = 49,
                            Column = 9,
                            Row = 5
                        },
                        new
                        {
                            Id = 50,
                            Column = 10,
                            Row = 5
                        },
                        new
                        {
                            Id = 51,
                            Column = 1,
                            Row = 6
                        },
                        new
                        {
                            Id = 52,
                            Column = 2,
                            Row = 6
                        },
                        new
                        {
                            Id = 53,
                            Column = 3,
                            Row = 6
                        },
                        new
                        {
                            Id = 54,
                            Column = 4,
                            Row = 6
                        },
                        new
                        {
                            Id = 55,
                            Column = 5,
                            Row = 6
                        },
                        new
                        {
                            Id = 56,
                            Column = 6,
                            Row = 6
                        },
                        new
                        {
                            Id = 57,
                            Column = 7,
                            Row = 6
                        },
                        new
                        {
                            Id = 58,
                            Column = 8,
                            Row = 6
                        },
                        new
                        {
                            Id = 59,
                            Column = 9,
                            Row = 6
                        },
                        new
                        {
                            Id = 60,
                            Column = 10,
                            Row = 6
                        },
                        new
                        {
                            Id = 61,
                            Column = 1,
                            Row = 7
                        },
                        new
                        {
                            Id = 62,
                            Column = 2,
                            Row = 7
                        },
                        new
                        {
                            Id = 63,
                            Column = 3,
                            Row = 7
                        },
                        new
                        {
                            Id = 64,
                            Column = 4,
                            Row = 7
                        },
                        new
                        {
                            Id = 65,
                            Column = 5,
                            Row = 7
                        },
                        new
                        {
                            Id = 66,
                            Column = 6,
                            Row = 7
                        },
                        new
                        {
                            Id = 67,
                            Column = 7,
                            Row = 7
                        },
                        new
                        {
                            Id = 68,
                            Column = 8,
                            Row = 7
                        },
                        new
                        {
                            Id = 69,
                            Column = 9,
                            Row = 7
                        },
                        new
                        {
                            Id = 70,
                            Column = 10,
                            Row = 7
                        },
                        new
                        {
                            Id = 71,
                            Column = 1,
                            Row = 8
                        },
                        new
                        {
                            Id = 72,
                            Column = 2,
                            Row = 8
                        },
                        new
                        {
                            Id = 73,
                            Column = 3,
                            Row = 8
                        },
                        new
                        {
                            Id = 74,
                            Column = 4,
                            Row = 8
                        },
                        new
                        {
                            Id = 75,
                            Column = 5,
                            Row = 8
                        },
                        new
                        {
                            Id = 76,
                            Column = 6,
                            Row = 8
                        },
                        new
                        {
                            Id = 77,
                            Column = 7,
                            Row = 8
                        },
                        new
                        {
                            Id = 78,
                            Column = 8,
                            Row = 8
                        },
                        new
                        {
                            Id = 79,
                            Column = 9,
                            Row = 8
                        },
                        new
                        {
                            Id = 80,
                            Column = 10,
                            Row = 8
                        },
                        new
                        {
                            Id = 81,
                            Column = 1,
                            Row = 9
                        },
                        new
                        {
                            Id = 82,
                            Column = 2,
                            Row = 9
                        },
                        new
                        {
                            Id = 83,
                            Column = 3,
                            Row = 9
                        },
                        new
                        {
                            Id = 84,
                            Column = 4,
                            Row = 9
                        },
                        new
                        {
                            Id = 85,
                            Column = 5,
                            Row = 9
                        },
                        new
                        {
                            Id = 86,
                            Column = 6,
                            Row = 9
                        },
                        new
                        {
                            Id = 87,
                            Column = 7,
                            Row = 9
                        },
                        new
                        {
                            Id = 88,
                            Column = 8,
                            Row = 9
                        },
                        new
                        {
                            Id = 89,
                            Column = 9,
                            Row = 9
                        },
                        new
                        {
                            Id = 90,
                            Column = 10,
                            Row = 9
                        },
                        new
                        {
                            Id = 91,
                            Column = 1,
                            Row = 10
                        },
                        new
                        {
                            Id = 92,
                            Column = 2,
                            Row = 10
                        },
                        new
                        {
                            Id = 93,
                            Column = 3,
                            Row = 10
                        },
                        new
                        {
                            Id = 94,
                            Column = 4,
                            Row = 10
                        },
                        new
                        {
                            Id = 95,
                            Column = 5,
                            Row = 10
                        },
                        new
                        {
                            Id = 96,
                            Column = 6,
                            Row = 10
                        },
                        new
                        {
                            Id = 97,
                            Column = 7,
                            Row = 10
                        },
                        new
                        {
                            Id = 98,
                            Column = 8,
                            Row = 10
                        },
                        new
                        {
                            Id = 99,
                            Column = 9,
                            Row = 10
                        },
                        new
                        {
                            Id = 100,
                            Column = 10,
                            Row = 10
                        });
                });

            modelBuilder.Entity("CinemaBooking.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CinemaBooking.API.Models.Reservation", b =>
                {
                    b.HasOne("CinemaBooking.API.Models.Screening", "Screening")
                        .WithMany("Reservations")
                        .HasForeignKey("ScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBooking.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screening");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaBooking.API.Models.ReservationSeat", b =>
                {
                    b.HasOne("CinemaBooking.API.Models.Reservation", "Reservation")
                        .WithMany("Seats")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBooking.API.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("CinemaBooking.API.Models.Screening", b =>
                {
                    b.HasOne("CinemaBooking.API.Models.Movie", "Movie")
                        .WithMany("Screenings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaBooking.API.Models.Movie", b =>
                {
                    b.Navigation("Screenings");
                });

            modelBuilder.Entity("CinemaBooking.API.Models.Reservation", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("CinemaBooking.API.Models.Screening", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
